// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wlQmqtbaXkzPJi8SDILsGQ2DzDtdn_0',
    appId: '1:259572475569:web:48260f23c4ec7dd9116490',
    messagingSenderId: '259572475569',
    projectId: 'capstone-ef0b5',
    authDomain: 'capstone-ef0b5.firebaseapp.com',
    storageBucket: 'capstone-ef0b5.firebasestorage.app',
    measurementId: 'G-6HTX0NK6NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsSVMDqtYUfGQjl3ukCBGSUZibxdlwJd8',
    appId: '1:264027375087:android:54f2e721c27de81a5ce21a',
    messagingSenderId: '264027375087',
    projectId: 'casaluxe-4b6ac',
    storageBucket: 'casaluxe-4b6ac.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wlQmqtbaXkzPJi8SDILsGQ2DzDtdn_0',
    appId: '1:259572475569:web:9226c58750739f6e116490',
    messagingSenderId: '259572475569',
    projectId: 'capstone-ef0b5',
    authDomain: 'capstone-ef0b5.firebaseapp.com',
    storageBucket: 'capstone-ef0b5.firebasestorage.app',
    measurementId: 'G-R7VXW9KSZY',
  );
}